[PHP]
engine = On
short_open_tag = Off
precision = 14
date.timezone = UTC
output_buffering = 4096
zlib.output_compression = Off
implicit_flush = Off
serialize_precision = -1
disable_functions = pcntl_alarm,pcntl_fork,pcntl_waitpid,pcntl_wait,pcntl_wifexited,pcntl_wifstopped,pcntl_wifsignaled,pcntl_wexitstatus,pcntl_wtermsig,pcntl_signal,pcntl_signal_dispatch,pcntl_get_last_error,pcntl_strerror,pcntl_sigprocmask,pcntl_sigpending,pcntl_sigtimedwait,pcntl_sigwaitinfo,pcntl_sighup,pcntl_sigint,pcntl_sigquit,pcntl_sigill,pcntl_sigtrap,pcntl_sigabrt,pcntl_sigbus,pcntl_sigfpe,pcntl_sigkill,pcntl_sigusr1,pcntl_sigusr2,pcntl_sigpipe,pcntl_sigalrm,pcntl_sigterm,pcntl_sigchld,pcntl_sigcld,pcntl_sigstack,pcntl_sigvtalrm,pcntl_sigprof,pcntl_sigwinch,pcntl_sigcont,pcntl_sigstop,pcntl_sigtstp,pcntl_sigttin,pcntl_sigttou,pcntl_sigpwr,pcntl_sigusr1,pcntl_sigusr2
max_execution_time = 60
max_input_time = 60
memory_limit = 256M
error_reporting = E_ALL & ~E_DEPRECATED & ~E_STRICT
display_errors = Off
display_startup_errors = Off
log_errors = On
error_log = /var/www/html/storage/logs/php-errors.log
post_max_size = 20M
upload_max_filesize = 20M
max_file_uploads = 20
cgi.fix_pathinfo = 0

[Assertion]
zend.assertions = -1
