[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0
pidfile=/tmp/supervisord.pid

[program:php-fpm]
command=/usr/local/sbin/php-fpm -F
autostart=true
autorestart=true
priority=10
stdout_logfile=/dev/null
stderr_logfile=/dev/null

[program:nginx]
command=/usr/sbin/nginx -g 'daemon off;'
autostart=true
autorestart=true
priority=20
stdout_logfile=/dev/null
stderr_logfile=/dev/null

[program:scheduler]
command=php /var/www/html/artisan schedule:work
directory=/var/www/html
autostart=true
autorestart=true
priority=30
stdout_logfile=/dev/null
stderr_logfile=/dev/null

[program:queue]
command=php /var/www/html/artisan queue:work --tries=3 --timeout=90 --memory=512
directory=/var/www/html
autostart=true
autorestart=true
priority=40
stdout_logfile=/dev/null
stderr_logfile=/dev/null
